---
- name: Get binary
  when:
    - fail2ban_exporter_binary_local_dir | length == 0
    - not fail2ban_exporter_skip_install
  block:

    - name: Download fail2ban_exporter binary to local folder
      become: false
      ansible.builtin.get_url:
        url: "{{ fail2ban_exporter_binary_url }}"
        dest: "{{ fail2ban_exporter_archive_path }}/fail2ban_exporter_{{ fail2ban_exporter_version }}_linux_{{ go_arch }}.tar.gz"
        checksum: "sha256:{{ __fail2ban_exporter_checksum }}"
        mode: '0644'
      register: _download_binary
      until: _download_binary is succeeded
      retries: 5
      delay: 2
      delegate_to: localhost
      check_mode: false

    - name: Unpack fail2ban_exporter binary
      become: false
      ansible.builtin.unarchive:
        src: "{{ fail2ban_exporter_archive_path }}/fail2ban_exporter_{{ fail2ban_exporter_version }}_linux_{{ go_arch }}.tar.gz"
        dest: "{{ fail2ban_exporter_archive_path }}"
        creates: "{{ fail2ban_exporter_archive_path }}/fail2ban_exporter"
      delegate_to: localhost
      check_mode: false

    - name: Propagate fail2ban_exporter binaries
      ansible.builtin.copy:
        src: "{{ fail2ban_exporter_archive_path }}/fail2ban_exporter"
        dest: "{{ fail2ban_exporter_binary_install_dir }}/fail2ban_exporter"
        mode: 0755
        owner: root
        group: root
      notify: restart fail2ban_exporter
      when: not ansible_check_mode

- name: Propagate locally distributed fail2ban_exporter binary
  ansible.builtin.copy:
    src: "{{ fail2ban_exporter_binary_local_dir }}/fail2ban_exporter"
    dest: "{{ fail2ban_exporter_binary_install_dir }}/fail2ban_exporter"
    mode: 0755
    owner: root
    group: root
  when:
    - fail2ban_exporter_binary_local_dir | length > 0
    - not fail2ban_exporter_skip_install
  notify: restart fail2ban_exporter
