---
cadvisor_version: 0.49.1
cadvisor_binary_url: "https://github.com/{{ _cadvisor_repo }}/releases/download/v{{ cadvisor_version }}/\
                      cadvisor-v{{ cadvisor_version }}-{{ ansible_system | lower }}-{{ _cadvisor_go_ansible_arch }}"

cadvisor_listen_ip: "0.0.0.0"
cadvisor_port: "8080"
cadvisor_prometheus_endpoint: "/metrics"

cadvisor_enable_metrics: []
cadvisor_disable_metrics: []
cadvisor_env_metadata_whitelist: []
cadvisor_whitelisted_container_labels: []
cadvisor_store_container_labels: true
cadvisor_docker_only: false

cadvisor_system_group: "root"
cadvisor_system_user: "{{ cadvisor_system_group }}"

# Local path to stash the archive and its extraction
cadvisor_local_cache_path: "/tmp/cadvisor-{{ ansible_system | lower }}-{{ _cadvisor_go_ansible_arch }}/{{ cadvisor_version }}"

cadvisor_binary_install_dir: "/usr/local/bin"
