---
# yamllint disable rule:line-length
argument_specs:
  main:
    short_description: "Prometheus ipmi_exporter"
    description:
      - "Deploy prometheus L(ipmi exporter,https://github.com/prometheus-community/ipmi_exporter) using ansible"
    author:
      - "Prometheus Community"
    options:
      ipmi_exporter_version:
        description: "ipmi_exporter package version. Also accepts latest as parameter."
        default: "1.8.0"
      ipmi_exporter_binary_url:
        description: "URL of the ipmi_exporter binaries .tar.gz file"
        default: "https://github.com/{{ _ipmi_exporter_repo }}/releases/download/v{{ ipmi_exporter_version }}/ipmi_exporter-{{ ipmi_exporter_version }}.{{ ansible_system | lower }}-{{ _ipmi_exporter_go_ansible_arch }}.tar.gz"
      ipmi_exporter_checksums_url:
        description: "URL of the ipmi_exporter checksums file"
        default: "https://github.com/{{ _ipmi_exporter_repo }}/releases/download/v{{ ipmi_exporter_version }}/sha256sums.txt"
      ipmi_exporter_modules:
        description:
          - "ipmi_exporter modules configuration"
          - "https://github.com/prometheus-community/ipmi_exporter#configuration"
        type: "dict"
      ipmi_exporter_web_listen_address:
        description: "Address on which ipmi exporter will listen"
        default: "0.0.0.0:9290"
      ipmi_exporter_tls_server_config:
        description:
          - "Configuration for TLS authentication."
          - "Keys and values are the same as in L(ipmi_exporter docs,https://github.com/prometheus/exporter-toolkit/blob/master/docs/web-configuration.md)."
        type: "dict"
      ipmi_exporter_http_server_config:
        description:
          - "Config for HTTP/2 support."
          - "Keys and values are the same as in L(ipmi_exporter docs,https://github.com/prometheus/exporter-toolkit/blob/master/docs/web-configuration.md)."
        type: "dict"
      ipmi_exporter_basic_auth_users:
        description: "Dictionary of users and password for basic authentication. Passwords are automatically hashed with bcrypt."
        type: "dict"
      ipmi_exporter_log_level:
        description: "Only log messages with the given severity or above. One of: [debug, info, warn, error]"
        default: "info"
      ipmi_exporter_log_format:
        description: "Output format of log messages. One of: [logfmt, json]"
        default: "logfmt"
      ipmi_exporter_binary_install_dir:
        description:
          - "I(Advanced)"
          - "Directory to install ipmi_exporter binary"
        default: "/usr/local/bin"
      ipmi_exporter_system_group:
        description:
          - "I(Advanced)"
          - "System group for ipmi_exporter"
        default: "ipmi-exp"
      ipmi_exporter_system_user:
        description:
          - "I(Advanced)"
          - "ipmi_exporter user"
        default: "ipmi-exp"
      ipmi_exporter_local_cache_path:
        description: "Local path to stash the archive and its extraction"
        default: "/tmp/ipmi_exporter-{{ ansible_system | lower }}-{{ _ipmi_exporter_go_ansible_arch }}/{{ ipmi_exporter_version }}"
      ipmi_exporter_config_dir:
        description: "Path to directory with ipmi_exporter configuration"
        default: "/etc/ipmi_exporter"
