---
galaxy_info:
  author: "Prometheus Community"
  description: "Prometheus ipmi_exporter"
  license: "Apache"
  min_ansible_version: "2.12"
  platforms:
    - name: "Ubuntu"
      versions:
        - "jammy"
        - "noble"
    - name: "Debian"
      versions:
        - "bullseye"
        - "bookworm"
    - name: "EL"
      versions:
        - "8"
        - "9"
  galaxy_tags:
    - "monitoring"
    - "prometheus"
    - "exporter"
    - "metrics"
    - "system"
