---
# yamllint disable rule:line-length
argument_specs:
  main:
    short_description: "Prometheus nginx_exporter"
    description:
      - "Deploy prometheus L(nginx exporter,https://github.com/nginxinc/nginx-prometheus-exporter) using ansible"
    author:
      - "Prometheus Community"
    options:
      nginx_exporter_version:
        description: "nginx_exporter package version. Also accepts latest as parameter."
        default: "1.3.0"
      nginx_exporter_plus:
        description: "Start the exporter for NGINX Plus."
        type: bool
        default: false
      nginx_exporter_binary_url:
        description: "URL of the nginx_exporter binaries .tar.gz file"
        default: "https://github.com/{{ _nginx_exporter_repo }}/releases/download/v{{ nginx_exporter_version }}/nginx-prometheus-exporter_{{ nginx_exporter_version }}_{{ ansible_system | lower }}_{{ _nginx_exporter_go_ansible_arch }}.tar.gz"
      nginx_exporter_checksums_url:
        description: "URL of the nginx_exporter checksums file"
        default: "https://github.com/{{ _nginx_exporter_repo }}/releases/download/v{{ nginx_exporter_version }}/nginx-prometheus-exporter_{{ nginx_exporter_version }}_checksums.txt"
      nginx_exporter_web_listen_address:
        description: "Address on which nginx exporter will listen"
        default: "0.0.0.0:9113"
      nginx_exporter_web_telemetry_path:
        description: "Path under which to expose metrics"
        default: "/metrics"
      nginx_exporter_tls_server_config:
        description:
          - "Configuration for TLS authentication."
          - "Keys and values are the same as in L(nginx_exporter docs,https://github.com/prometheus/exporter-toolkit/blob/master/docs/web-configuration.md)."
        type: "dict"
      nginx_exporter_http_server_config:
        description:
          - "Config for HTTP/2 support."
          - "Keys and values are the same as in L(nginx_exporter docs,https://github.com/prometheus/exporter-toolkit/blob/master/docs/web-configuration.md)."
        type: "dict"
      nginx_exporter_basic_auth_users:
        description: "Dictionary of users and password for basic authentication. Passwords are automatically hashed with bcrypt."
        type: "dict"
      nginx_exporter_log_level:
        description: "Only log messages with the given severity or above. One of: [debug, info, warn, error]"
        default: "info"
      nginx_exporter_log_format:
        description: "Output format of log messages. One of: [logfmt, json]"
        default: "logfmt"
      nginx_exporter_scrape_uri:
        description: "A URI or unix domain socket path for scraping NGINX or NGINX Plus metrics. For NGINX, the stub_status page must be available through the URI."
        default: "http://127.0.0.1/stub_status"
      nginx_exporter_binary_install_dir:
        description:
          - "I(Advanced)"
          - "Directory to install nginx_exporter binary"
        default: "/usr/local/bin"
      nginx_exporter_system_group:
        description:
          - "I(Advanced)"
          - "System group for nginx_exporter"
        default: "nginx-exp"
      nginx_exporter_system_user:
        description:
          - "I(Advanced)"
          - "nginx_exporter user"
        default: "nginx-exp"
      nginx_exporter_local_cache_path:
        description: "Local path to stash the archive and its extraction"
        default: "/tmp/nginx_exporter-{{ ansible_system | lower }}-{{ _nginx_exporter_go_ansible_arch }}/{{ nginx_exporter_version }}"
      nginx_exporter_config_dir:
        description: "Path to directory with nginx_exporter configuration"
        default: "/etc/nginx_exporter"
