---
_blackbox_exporter_go_ansible_arch: "{{ {'i386': '386',
                                     'x86_64': 'amd64',
                                     'aarch64': 'arm64',
                                     'armv7l': 'armv7',
                                     'armv6l': 'armv6'}.get(ansible_facts['architecture'], ansible_facts['architecture']) }}"
_blackbox_exporter_repo: "prometheus/blackbox_exporter"
_github_api_headers: "{{ {'GITHUB_TOKEN': lookup('ansible.builtin.env', 'GITHUB_TOKEN')} if (lookup('ansible.builtin.env', 'GITHUB_TOKEN')) else {} }}"
_blackbox_exporter_binaries: ['blackbox_exporter']
_blackbox_exporter_dependencies: "{% if (ansible_facts['pkg_mgr'] == 'apt') %}\
                                  {{ (['python-apt', 'libcap2-bin'] if ansible_facts['python_version'] is version('3', '<') else ['python3-apt', 'libcap2-bin']) }}\
                                  {% else %}\
                                  {% endif %}"
