---
nginx_exporter_version: 1.3.0
nginx_exporter_binary_url: "https://github.com/{{ _nginx_exporter_repo }}/releases/download/v{{ nginx_exporter_version }}/\
                          nginx-prometheus-exporter_{{ nginx_exporter_version }}_{{ ansible_system | lower }}_{{ _nginx_exporter_go_ansible_arch }}.tar.gz"
nginx_exporter_checksums_url: "https://github.com/{{ _nginx_exporter_repo }}/releases/download/v{{ nginx_exporter_version }}/\
                          nginx-prometheus-exporter_{{ nginx_exporter_version }}_checksums.txt"
nginx_exporter_plus: false
nginx_exporter_scrape_uri: "http://127.0.0.1/stub_status"
nginx_exporter_web_listen_address: "0.0.0.0:9113"
nginx_exporter_web_telemetry_path: "/metrics"

nginx_exporter_tls_server_config: {}

nginx_exporter_http_server_config: {}

nginx_exporter_basic_auth_users: {}

nginx_exporter_log_level: "info"
nginx_exporter_log_format: "logfmt"

nginx_exporter_binary_install_dir: "/usr/local/bin"
nginx_exporter_system_group: "nginx-exp"
nginx_exporter_system_user: "{{ nginx_exporter_system_group }}"

nginx_exporter_config_dir: "/etc/nginx_exporter"

# Local path to stash the archive and its extraction
nginx_exporter_local_cache_path: "/tmp/nginx_exporter-{{ ansible_system | lower }}-{{ _nginx_exporter_go_ansible_arch }}/{{ nginx_exporter_version }}"
