---
- name: Create the memcached_exporter group
  ansible.builtin.group:
    name: "{{ memcached_exporter_system_group }}"
    state: present
    system: true
  when: memcached_exporter_system_group != "root"

- name: Create the memcached_exporter user
  ansible.builtin.user:
    name: "{{ memcached_exporter_system_user }}"
    groups: "{{ memcached_exporter_system_group }}"
    append: true
    shell: /usr/sbin/nologin
    system: true
    create_home: false
    home: /
  when: memcached_exporter_system_user != "root"

- name: Get binary
  when:
    - memcached_exporter_binary_local_dir | length == 0
    - not memcached_exporter_skip_install
  block:

    - name: Download memcached_exporter binary to local folder
      become: false
      ansible.builtin.get_url:
        url: "{{ memcached_exporter_binary_url }}"
        dest: "{{ memcached_exporter_archive_path }}/memcached_exporter-{{ memcached_exporter_version }}.linux-{{ go_arch }}.tar.gz"
        checksum: "sha256:{{ __memcached_exporter_checksum }}"
        mode: '0644'
      register: _download_binary
      until: _download_binary is succeeded
      retries: 5
      delay: 2
      delegate_to: localhost
      check_mode: false

    - name: Unpack memcached_exporter binary
      become: false
      ansible.builtin.unarchive:
        src: "{{ memcached_exporter_archive_path }}/memcached_exporter-{{ memcached_exporter_version }}.linux-{{ go_arch }}.tar.gz"
        dest: "{{ memcached_exporter_archive_path }}"
        creates: "{{ memcached_exporter_archive_path }}/memcached_exporter-{{ memcached_exporter_version }}.linux-{{ go_arch }}/memcached_exporter"
      delegate_to: localhost
      check_mode: false

    - name: Propagate memcached_exporter binaries
      ansible.builtin.copy:
        src: "{{ memcached_exporter_archive_path }}/memcached_exporter-{{ memcached_exporter_version }}.linux-{{ go_arch }}/memcached_exporter"
        dest: "{{ memcached_exporter_binary_install_dir }}/memcached_exporter"
        mode: 0755
        owner: root
        group: root
      notify: restart memcached_exporter
      when: not ansible_check_mode

- name: Propagate locally distributed memcached_exporter binary
  ansible.builtin.copy:
    src: "{{ memcached_exporter_binary_local_dir }}/memcached_exporter"
    dest: "{{ memcached_exporter_binary_install_dir }}/memcached_exporter"
    mode: 0755
    owner: root
    group: root
  when:
    - memcached_exporter_binary_local_dir | length > 0
    - not memcached_exporter_skip_install
  notify: restart memcached_exporter
