---
- name: Preflight
  ansible.builtin.include_tasks:
    file: preflight.yml
  tags:
    - memcached_exporter_install
    - memcached_exporter_configure
    - memcached_exporter_run

- name: Install
  ansible.builtin.include_role:
    name: prometheus.prometheus._common
    tasks_from: install.yml
  vars:
    _common_local_cache_path: "{{ memcached_exporter_local_cache_path }}"
    _common_binaries: "{{ _memcached_exporter_binaries }}"
    _common_binary_install_dir: "{{ memcached_exporter_binary_install_dir }}"
    _common_binary_url: "{{ memcached_exporter_binary_url }}"
    _common_checksums_url: "{{ memcached_exporter_checksums_url }}"
    _common_system_group: "{{ memcached_exporter_system_group }}"
    _common_system_user: "{{ memcached_exporter_system_user }}"
    _common_config_dir: "{{ memcached_exporter_config_dir }}"
    _common_binary_unarchive_opts: ['--strip-components=1']
  tags:
    - memcached_exporter_install

- name: SELinux
  ansible.builtin.include_role:
    name: prometheus.prometheus._common
    tasks_from: selinux.yml
  vars:
    _common_selinux_port: "{{ memcached_exporter_web_listen_address | urlsplit('port') }}"
  when: ansible_selinux.status == "enabled"
  tags:
    - memcached_exporter_configure

- name: Configure
  ansible.builtin.include_role:
    name: prometheus.prometheus._common
    tasks_from: configure.yml
  vars:
    _common_system_user: "{{ memcached_exporter_system_user }}"
    _common_system_group: "{{ memcached_exporter_system_group }}"
    _common_config_dir: "{{ memcached_exporter_config_dir }}"
    _common_tls_server_config: "{{ memcached_exporter_tls_server_config }}"
    _common_http_server_config: "{{ memcached_exporter_http_server_config }}"
    _common_basic_auth_users: "{{ memcached_exporter_basic_auth_users }}"
  tags:
    - memcached_exporter_configure

- name: Ensure memcached_exporter is enabled on boot
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: memcached_exporter
    enabled: true
    state: started
  when:
    - not ansible_check_mode
  tags:
    - memcached_exporter_run
