---
- name: Common preflight
  ansible.builtin.include_role:
    name: prometheus.prometheus._common
    tasks_from: preflight.yml
  vars:
    _common_dependencies: "{{ _ipmi_exporter_dependencies }}"

- name: Assert that used version supports listen address type
  ansible.builtin.assert:
    that:
      - >-
        ipmi_exporter_web_listen_address is string

- name: Naive assertion of proper listen address
  ansible.builtin.assert:
    that:
      - >-
        [ipmi_exporter_web_listen_address] |
          flatten |
          reject('match', '.+:\\d+$') |
          list |
          length == 0

- name: Assert that TLS config is correct
  when: ipmi_exporter_tls_server_config | length > 0
  block:
    - name: Assert that TLS key and cert path are set
      ansible.builtin.assert:
        that:
          - "ipmi_exporter_tls_server_config.cert_file is defined"
          - "ipmi_exporter_tls_server_config.key_file is defined"

    - name: Check existence of TLS cert file
      ansible.builtin.stat:
        path: "{{ ipmi_exporter_tls_server_config.cert_file }}"
      register: __ipmi_exporter_cert_file

    - name: Check existence of TLS key file
      ansible.builtin.stat:
        path: "{{ ipmi_exporter_tls_server_config.key_file }}"
      register: __ipmi_exporter_key_file

    - name: Assert that TLS key and cert are present
      ansible.builtin.assert:
        that:
          - "__ipmi_exporter_cert_file.stat.exists"
          - "__ipmi_exporter_key_file.stat.exists"

- name: Discover latest version
  ansible.builtin.set_fact:
    ipmi_exporter_version: "{{ (lookup('url', 'https://api.github.com/repos/{{ _ipmi_exporter_repo }}/releases/latest', headers=_github_api_headers,
                            split_lines=False) | from_json).get('tag_name') | replace('v', '') }}"
  run_once: true
  until: ipmi_exporter_version is version('0.0.0', '>=')
  retries: 10
  when:
    - ipmi_exporter_version == "latest"
  tags:
    - ipmi_exporter
    - install
    - ipmi_exporter_install
    - download
    - ipmi_exporter_download
