---
- name: Create the cadvisor group
  ansible.builtin.group:
    name: "{{ cadvisor_system_group }}"
    state: present
    system: true
  when: cadvisor_system_group != "root"

- name: Create the cadvisor user
  ansible.builtin.user:
    name: "{{ cadvisor_system_user }}"
    groups: "{{ cadvisor_system_group }}"
    append: true
    shell: /usr/sbin/nologin
    system: true
    create_home: false
    home: /
  when: cadvisor_system_user != "root"

- name: Get binary
  when:
    - cadvisor_binary_local_dir | length == 0
    - not cadvisor_skip_install
  block:

    - name: Download cadvisor binary to local folder
      become: false
      ansible.builtin.get_url:
        url: "{{ cadvisor_binary_url }}"
        dest: "/tmp/cadvisor-v{{ cadvisor_version }}-linux-{{ go_arch }}"
        mode: '0644'
      register: _download_binary
      until: _download_binary is succeeded
      retries: 5
      delay: 2
      delegate_to: localhost
      check_mode: false

    - name: Propagate cadvisor binaries
      ansible.builtin.copy:
        src: "/tmp/cadvisor-v{{ cadvisor_version }}-linux-{{ go_arch }}"
        dest: "{{ cadvisor_binary_install_dir }}/cadvisor"
        mode: 0755
        owner: root
        group: root
      notify: restart cadvisor
      when: not ansible_check_mode

- name: Propagate locally distributed cadvisor binary
  ansible.builtin.copy:
    src: "{{ cadvisor_binary_local_dir }}/cadvisor"
    dest: "{{ cadvisor_binary_install_dir }}/cadvisor"
    mode: 0755
    owner: root
    group: root
  when:
    - cadvisor_binary_local_dir | length > 0
    - not cadvisor_skip_install
  notify: restart cadvisor
