---
_systemd_exporter_go_ansible_arch: "{{ {'i386': '386',
                                    'x86_64': 'amd64',
                                    'aarch64': 'arm64',
                                    'armv7l': 'armv7',
                                    'armv6l': 'armv6'}.get(ansible_architecture, ansible_architecture) }}"
_systemd_exporter_repo: "prometheus-community/systemd_exporter"
_github_api_headers: "{{ {'GITHUB_TOKEN': lookup('ansible.builtin.env', 'GITHUB_TOKEN')} if (lookup('ansible.builtin.env', 'GITHUB_TOKEN')) else {} }}"
_systemd_exporter_binaries: ['systemd_exporter']
