---
- name: Assert usage of systemd as an init system
  ansible.builtin.assert:
    that: ansible_service_mgr == 'systemd'
    msg: "This role only works with systemd"

- name: Install package fact dependencies
  become: true
  ansible.builtin.package:
    name: "{{ _pkg_fact_req }}"
    state: present
  when: (_pkg_fact_req)
  vars:
    _pkg_fact_req: "{% if (ansible_pkg_mgr == 'apt') %}\
                    {{ ('python-apt' if ansible_python_version is version('3', '<') else 'python3-apt') }}
                    {% else %}\
                    {% endif %}"

- name: Gather package facts
  ansible.builtin.package_facts:
  when: "not 'packages' in ansible_facts"

- name: Assert that used version supports listen address type
  ansible.builtin.assert:
    that:
      - >-
        postgres_exporter_web_listen_address is string
        or
        (
          postgres_exporter_version is version('0.15.0', '>=') and
          postgres_exporter_web_listen_address | type_debug == "list"
        )

- name: Naive assertion of proper listen address
  ansible.builtin.assert:
    that:
      - >-
        [postgres_exporter_web_listen_address] |
          flatten |
          reject('match', '.+:\\d+$') |
          list |
          length == 0

- name: Assert collectors are not both disabled and enabled at the same time
  ansible.builtin.assert:
    that:
      - "item not in postgres_exporter_enabled_collectors"
  with_items: "{{ postgres_exporter_disabled_collectors }}"

- name: Assert that TLS config is correct
  when: postgres_exporter_tls_server_config | length > 0
  block:
    - name: Assert that TLS key and cert path are set
      ansible.builtin.assert:
        that:
          - "postgres_exporter_tls_server_config.cert_file is defined"
          - "postgres_exporter_tls_server_config.key_file is defined"

    - name: Check existence of TLS cert file
      ansible.builtin.stat:
        path: "{{ postgres_exporter_tls_server_config.cert_file }}"
      register: __postgres_exporter_cert_file

    - name: Check existence of TLS key file
      ansible.builtin.stat:
        path: "{{ postgres_exporter_tls_server_config.key_file }}"
      register: __postgres_exporter_key_file

    - name: Assert that TLS key and cert are present
      ansible.builtin.assert:
        that:
          - "__postgres_exporter_cert_file.stat.exists"
          - "__postgres_exporter_key_file.stat.exists"

- name: Check if postgres_exporter is installed
  ansible.builtin.stat:
    path: "{{ postgres_exporter_binary_install_dir }}/postgres_exporter"
  register: __postgres_exporter_is_installed
  check_mode: false
  tags:
    - postgres_exporter_install

- name: Gather currently installed postgres_exporter version (if any)
  ansible.builtin.command: "{{ postgres_exporter_binary_install_dir }}/postgres_exporter --version"
  changed_when: false
  register: __postgres_exporter_current_version_output
  check_mode: false
  when: __postgres_exporter_is_installed.stat.exists
  tags:
    - postgres_exporter_install

- name: Discover latest version
  ansible.builtin.set_fact:
    postgres_exporter_version: "{{ (lookup('url', 'https://api.github.com/repos/{{ _postgres_exporter_repo }}/releases/latest', headers=_github_api_headers,
                              split_lines=False) | from_json).get('tag_name') | replace('v', '') }}"
  run_once: true
  until: postgres_exporter_version is version('0.0.0', '>=')
  retries: 10
  when:
    - postgres_exporter_version == "latest"
    - postgres_exporter_binary_local_dir | length == 0
    - not postgres_exporter_skip_install

- name: Get postgres_exporter binary checksum
  when:
    - postgres_exporter_binary_local_dir | length == 0
    - not postgres_exporter_skip_install
  block:
    - name: Get checksum list from github
      ansible.builtin.set_fact:
        __postgres_exporter_checksums: "{{ lookup('url', postgres_exporter_checksums_url, headers=_github_api_headers, wantlist=True) | list }}"
      run_once: true
      until: __postgres_exporter_checksums is search('linux-' + go_arch + '.tar.gz')
      retries: 10

    - name: "Get checksum for {{ go_arch }}"
      ansible.builtin.set_fact:
        __postgres_exporter_checksum: "{{ item.split(' ')[0] }}"
      with_items: "{{ __postgres_exporter_checksums }}"
      when:
        - "('linux-' + go_arch + '.tar.gz') in item"
