---
# yamllint disable rule:line-length
argument_specs:
  main:
    short_description: "Prometheus apache_exporter"
    description:
      - "Deploy prometheus L(apache exporter,https://github.com/Lusitaniae/apache_exporter) using ansible"
    author:
      - "Prometheus Community"
    options:
      apache_exporter_version:
        description: "apache_exporter package version. Also accepts latest as parameter."
        default: "1.0.9"
      apache_exporter_binary_url:
        description: "URL of the apache_exporter binaries .tar.gz file"
        default: "https://github.com/{{ _apache_exporter_repo }}/releases/download/v{{ apache_exporter_version }}/apache_exporter_{{ apache_exporter_version }}_{{ ansible_facts['system'] | lower }}-{{ _apache_exporter_go_ansible_arch }}.tar.gz"
      apache_exporter_checksums_url:
        description: "URL of the apache_exporter checksums file"
        default: "https://github.com/{{ _apache_exporter_repo }}/releases/download/v{{ apache_exporter_version }}/apache_exporter_{{ apache_exporter_version }}_checksums.txt"
      apache_exporter_web_listen_address:
        description: "Address on which apache exporter will listen"
        default: "0.0.0.0:9117"
      apache_exporter_web_telemetry_path:
        description: "Path under which to expose metrics"
        default: "/metrics"
      apache_exporter_uri:
        description: "URI to scrape apache metrics"
        default: "http://localhost/server-status/?auto"
      apache_exporter_timeout_offset:
        description: "Offset to add to the timeout for the scrape"
        default: 1
      apache_exporter_tls_server_config:
        description:
          - "Configuration for TLS authentication."
          - "Keys and values are the same as in L(apache_exporter docs,https://github.com/prometheus/exporter-toolkit/blob/master/docs/web-configuration.md)."
        type: "dict"
      apache_exporter_http_server_config:
        description:
          - "Config for HTTP/2 support."
          - "Keys and values are the same as in L(apache_exporter docs,https://github.com/prometheus/exporter-toolkit/blob/master/docs/web-configuration.md)."
        type: "dict"
      apache_exporter_basic_auth_users:
        description: "Dictionary of users and password for basic authentication. Passwords are automatically hashed with bcrypt."
        type: "dict"
      apache_exporter_log_level:
        description: "Only log messages with the given severity or above. One of: [debug, info, warn, error]"
        default: "error"
      apache_exporter_binary_install_dir:
        description:
          - "I(Advanced)"
          - "Directory to install apache_exporter binary"
        default: "/usr/local/bin"
      apache_exporter_system_user:
        description:
          - "I(Advanced)"
          - "System user for apache_exporter"
        default: "apache-exp"
      apache_exporter_system_group:
        description:
          - "I(Advanced)"
          - "System group for apache_exporter"
        default: "apache-exp"
      apache_exporter_config_dir:
        description:
          - "I(Advanced)"
          - "Directory to store apache_exporter configuration"
        default: "/etc/apache_exporter"
      apache_exporter_local_cache_path:
        description:
          - "I(Advanced)"
          - "Local path to stash the archive and its extraction"
        default: "/tmp/apache_exporter-{{ ansible_facts['system'] | lower }}-{{ _apache_exporter_go_ansible_arch }}/{{ apache_exporter_version }}"
