---
_mysqld_exporter_go_ansible_arch: "{{ {'i386': '386',
                                   'x86_64': 'amd64',
                                   'aarch64': 'arm64',
                                   'armv7l': 'armv7',
                                   'armv6l': 'armv6'}.get(ansible_architecture, ansible_architecture) }}"
_mysqld_exporter_repo: "prometheus/mysqld_exporter"
_github_api_headers: "{{ {'GITHUB_TOKEN': lookup('ansible.builtin.env', 'GITHUB_TOKEN')} if (lookup('ansible.builtin.env', 'GITHUB_TOKEN')) else {} }}"
_mysqld_exporter_binaries: ['mysqld_exporter']
