---
ipmi_exporter_version: 1.8.0
ipmi_exporter_binary_url: "https://github.com/{{ _ipmi_exporter_repo }}/releases/download/v{{ ipmi_exporter_version }}/\
                           ipmi_exporter-{{ ipmi_exporter_version }}.{{ ansible_system | lower }}-{{ _ipmi_exporter_go_ansible_arch }}.tar.gz"
ipmi_exporter_checksums_url: "https://github.com/{{ _ipmi_exporter_repo }}/releases/download/v{{ ipmi_exporter_version }}/sha256sums.txt"

ipmi_exporter_modules:
  default:
    collectors:
      - bmc
      - ipmi
      - dcmi
      - chassis
      - sel

ipmi_exporter_web_listen_address: "0.0.0.0:9290"

ipmi_exporter_tls_server_config: {}
ipmi_exporter_http_server_config: {}
ipmi_exporter_basic_auth_users: {}

ipmi_exporter_log_level: "info"
ipmi_exporter_log_format: "logfmt"

ipmi_exporter_binary_install_dir: "/usr/local/bin"
ipmi_exporter_system_user: "ipmi-exp"
ipmi_exporter_system_group: "{{ ipmi_exporter_system_user }}"

ipmi_exporter_config_dir: /etc/ipmi_exporter

# Local path to stash the archive and its extraction
ipmi_exporter_local_cache_path: "/tmp/ipmi_exporter-{{ ansible_system | lower }}-{{ _ipmi_exporter_go_ansible_arch }}/{{ ipmi_exporter_version }}"
