---
provisioner:
  inventory:
    group_vars:
      all:
        pushgateway_binary_local_dir: "/tmp/pushgateway-linux-amd64"
        pushgateway_web_listen_address:
          - '127.0.0.1:8080'
          - '127.0.1.1:8080'
        pushgateway_tls_server_config:
          cert_file: /etc/pushgateway/tls.cert
          key_file: /etc/pushgateway/tls.key
        pushgateway_http_server_config:
          http2: true
        pushgateway_basic_auth_users:
          randomuser: examplepassword
        go_arch: amd64
        pushgateway_version: 1.5.1
