---
- name: Copy amtool config
  ansible.builtin.template:
    force: true
    src: "{{ alertmanager_amtool_config_file }}"
    dest: "{{ _alertmanager_amtool_config_dir }}/config.yml"
    owner: alertmanager
    group: alertmanager
    mode: 0644

- name: Copy alertmanager config
  ansible.builtin.template:
    force: true
    src: "{{ alertmanager_config_file }}"
    dest: "{{ alertmanager_config_dir }}/alertmanager.yml"
    owner: alertmanager
    group: alertmanager
    mode: 0644
    validate: "{{ _alertmanager_binary_install_dir }}/amtool check-config %s"
  notify:
    - restart alertmanager

- name: Create systemd service unit
  ansible.builtin.template:
    src: alertmanager.service.j2
    dest: /etc/systemd/system/alertmanager.service
    owner: root
    group: root
    mode: 0644
  notify:
    - restart alertmanager

- name: Copy alertmanager template files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ alertmanager_config_dir }}/templates/"
    force: true
    owner: alertmanager
    group: alertmanager
    mode: 0644
  with_fileglob: "{{ alertmanager_template_files }}"
  notify:
    - restart alertmanager
