---
- name: create alertmanager system group
  group:
    name: alertmanager
    system: true
    state: present

- name: create alertmanager system user
  user:
    name: alertmanager
    system: true
    shell: "/usr/sbin/nologin"
    group: alertmanager
    createhome: false

- name: create alertmanager directories
  file:
    path: "{{ item }}"
    state: directory
    owner: alertmanager
    group: alertmanager
    mode: 0755
  with_items:
    - "{{ alertmanager_config_dir }}"
    - "{{ alertmanager_config_dir }}/templates"
    - "{{ alertmanager_db_dir }}"
    - "{{ _alertmanager_amtool_config_dir }}"

- block:
    - name: download alertmanager binary to local folder
      become: false
      get_url:
        url: "https://github.com/prometheus/alertmanager/releases/download/v{{ alertmanager_version }}/alertmanager-{{ alertmanager_version }}.linux-{{ go_arch }}.tar.gz"
        dest: "/tmp/alertmanager-{{ alertmanager_version }}.linux-{{ go_arch }}.tar.gz"
        checksum: "sha256:{{ __alertmanager_checksum }}"
      register: _download_archive
      until: _download_archive is succeeded
      retries: 5
      delay: 2
      # run_once: true # <-- this can't be set due to multi-arch support
      delegate_to: localhost
      check_mode: false

    - name: unpack alertmanager binaries
      become: false
      unarchive:
        src: "/tmp/alertmanager-{{ alertmanager_version }}.linux-{{ go_arch }}.tar.gz"
        dest: "/tmp"
        mode: 0755
        creates: "/tmp/alertmanager-{{ alertmanager_version }}.linux-{{ go_arch }}/alertmanager"
      delegate_to: localhost
      check_mode: false

    - name: propagate official alertmanager and amtool binaries
      copy:
        src: "/tmp/alertmanager-{{ alertmanager_version }}.linux-{{ go_arch }}/{{ item }}"
        dest: "{{ _alertmanager_binary_install_dir }}/{{ item }}"
        mode: 0755
        owner: root
        group: root
      with_items:
        - alertmanager
        - amtool
      notify:
        - restart alertmanager
  when: alertmanager_binary_local_dir | length == 0

- name: propagate locally distributed alertmanager and amtool binaries
  copy:
    src: "{{ alertmanager_binary_local_dir }}/{{ item }}"
    dest: "{{ _alertmanager_binary_install_dir }}/{{ item }}"
    mode: 0755
    owner: root
    group: root
  with_items:
    - alertmanager
    - amtool
  when: alertmanager_binary_local_dir | length > 0
  notify:
    - restart alertmanager
