---
# yamllint disable rule:line-length
argument_specs:
  main:
    short_description: "Prometheus Process exporter"
    description:
      - "Deploy prometheus L(Process exporter,https://github.com/ncabatoff/process-exporter) using ansible"
    author:
      - "Prometheus Community"
    options:
      process_exporter_version:
        description: "Process exporter package version. Also accepts latest as parameter."
        default: "0.8.3"
      process_exporter_binary_url:
        description: "URL of the Process exporter binaries .tar.gz file"
        default: "https://github.com/{{ _process_exporter_repo }}/releases/download/v{{ process_exporter_version }}/process-exporter-{{ process_exporter_version }}.{{ ansible_system | lower }}-{{ _process_exporter_go_ansible_arch }}.tar.gz"
      process_exporter_checksums_url:
        description: "URL of the Process exporter checksums file"
        default: "https://github.com/{{ _process_exporter_repo }}/releases/download/v{{ process_exporter_version }}/checksums.txt"
      process_exporter_web_listen_address:
        description: "Address on which Process exporter will listen"
        default: "0.0.0.0:9256"
      process_exporter_web_telemetry_path:
        description: "Path under which to expose metrics"
        default: "/metrics"
      process_exporter_tls_server_config:
        description:
          - "Configuration for TLS authentication."
        type: "dict"
      process_exporter_http_server_config:
        description:
          - "Config for HTTP/2 support."
        type: "dict"
      process_exporter_basic_auth_users:
        description: "Dictionary of users and password for basic authentication. Passwords are automatically hashed with bcrypt."
        type: "dict"
      process_exporter_names:
        description:
          - "Processes which should be monitored."
          - "Syntax is the same as in"
          - "L(using-a-config-file Default is consistent with deb/rpm packages,https://github.com/ncabatoff/process-exporter#using-a-config-file Default is consistent with deb/rpm packages)"
        default: !unsafe "[{name: '{{.Comm}}', cmdline: [.+]}]"
      process_exporter_binary_install_dir:
        description:
          - "I(Advanced)"
          - "Directory to install process_exporter binary"
        default: "/usr/local/bin"
      process_exporter_system_group:
        description:
          - "I(Advanced)"
          - "System group for Process exporter"
        default: "process-exp"
      process_exporter_system_user:
        description:
          - "I(Advanced)"
          - "Process exporter user"
        default: "process-exp"
      process_exporter_local_cache_path:
        description: "Local path to stash the archive and its extraction"
        default: "/tmp/process_exporter-{{ ansible_system | lower }}-{{ _process_exporter_go_ansible_arch }}/{{ process_exporter_version }}"
      process_exporter_config_dir:
        description: "Path to directory with process_exporter configuration"
        default: "/etc/process_exporter"
