---
mysqld_exporter_version: 0.15.1
mysqld_exporter_binary_local_dir: ""
mysqld_exporter_binary_url: "https://github.com/{{ _mysqld_exporter_repo }}/releases/download/v{{ mysqld_exporter_version }}/\
                           mysqld_exporter-{{ mysqld_exporter_version }}.linux-{{ go_arch }}.tar.gz"
mysqld_exporter_checksums_url: "https://github.com/{{ _mysqld_exporter_repo }}/releases/download/v{{ mysqld_exporter_version }}/sha256sums.txt"
mysqld_exporter_skip_install: false

mysqld_exporter_web_listen_address: "0.0.0.0:9104"
mysqld_exporter_web_telemetry_path: "/metrics"

mysqld_exporter_username: exporter
mysqld_exporter_password: secret

mysqld_exporter_config_file: "mysqld_exporter.cnf"
mysqld_exporter_host: null
mysqld_exporter_port: null
mysqld_exporter_socket: "/run/mysqld/mysqld.sock"

mysqld_exporter_tls_server_config: {}

mysqld_exporter_http_server_config: {}

mysqld_exporter_basic_auth_users: {}

mysqld_exporter_enabled_collectors: []
#  - engine_innodb_status
#  - perf_schema.eventsstatements

mysqld_exporter_disabled_collectors: []

# Internal variables.
mysqld_exporter_binary_install_dir: "/usr/local/bin"
mysqld_exporter_config_dir: "/etc/mysqld_exporter"
mysqld_exporter_system_group: "mysqld-exp"
mysqld_exporter_system_user: "{{ mysqld_exporter_system_group }}"
