---
redis_exporter_version: 1.63.0
redis_exporter_binary_url: "https://github.com/{{ _redis_exporter_repo }}/releases/download/v{{ redis_exporter_version }}/\
                           redis_exporter-v{{ redis_exporter_version }}.{{ ansible_system | lower }}-{{ _redis_exporter_go_ansible_arch }}.tar.gz"
redis_exporter_checksums_url: "https://github.com/{{ _redis_exporter_repo }}/releases/download/v{{ redis_exporter_version }}/sha256sums.txt"

# https://github.com/oliver006/redis_exporter?tab=readme-ov-file#command-line-flags
redis_exporter_addr: "redis://localhost:6379"
redis_exporter_user: ""
redis_exporter_password: ""
redis_exporter_passwords: {}
redis_exporter_check_keys: []
redis_exporter_check_single_keys: []
redis_exporter_check_streams: []
redis_exporter_check_single_streams: []
redis_exporter_check_keys_batch_size: 1000
redis_exporter_count_keys: []
redis_exporter_script: []
redis_exporter_debug: false
redis_exporter_log_format: "txt"
redis_exporter_namespace: "redis"
redis_exporter_connection_timeout: "15s"
redis_exporter_web_listen_address: "0.0.0.0:9121"
redis_exporter_web_telemetry_path: "/metrics"
redis_exporter_redis_only_metrics: false
redis_exporter_incl_config_metrics: false
redis_exporter_incl_system_metrics: false
redis_exporter_redact_config_metrics: false
redis_exporter_ping_on_connect: false
redis_exporter_is_tile38: false
redis_exporter_is_cluster: false
redis_exporter_export_client_list: false
redis_exporter_export_client_port: false
redis_exporter_skip_tls_verification: false
redis_exporter_tls_client_key_file: ""
redis_exporter_tls_client_cert_file: ""
redis_exporter_tls_server_key_file: ""
redis_exporter_tls_server_cert_file: ""
redis_exporter_tls_server_ca_cert_file: ""
redis_exporter_tls_server_min_version: "TLS1.2"
redis_exporter_tls_ca_cert_file: ""
redis_exporter_set_client_name: true
redis_exporter_check_key_groups: []
redis_exporter_max_distinct_key_groups: 100
redis_exporter_config_command: "CONFIG"

redis_exporter_binary_install_dir: "/usr/local/bin"
redis_exporter_system_group: "redis-exp"
redis_exporter_system_user: "{{ redis_exporter_system_group }}"
redis_exporter_config_dir: "/etc/redis_exporter"

# Local path to stash the archive and its extraction
redis_exporter_local_cache_path: "/tmp/redis_exporter-{{ ansible_system | lower }}-{{ _redis_exporter_go_ansible_arch }}/{{ redis_exporter_version }}"
