---
# yamllint disable rule:line-length
argument_specs:
  main:
    short_description: "Prometheus Node Exporter"
    description:
      - "Deploy prometheus L(node exporter,https://github.com/prometheus/node_exporter) using ansible"
    author:
      - "Prometheus Community"
    options:
      node_exporter_version:
        description: "Node exporter package version. Also accepts latest as parameter."
        default: "1.6.1"
      node_exporter_skip_install:
        description: "Node exporter installation tasks gets skipped when set to true."
        type: bool
        default: false
      node_exporter_binary_local_dir:
        description:
          - "Enables the use of local packages instead of those distributed on github."
          - "The parameter may be set to a directory where the C(node_exporter) binary is stored on the host where ansible is run."
          - "This overrides the I(node_exporter_version) parameter"
      node_exporter_binary_url:
        description: "URL of the node exporter binaries .tar.gz file"
        default: "https://github.com/{{ _node_exporter_repo }}/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-{{ go_arch }}.tar.gz"
      node_exporter_checksums_url:
        description: "URL of the node exporter checksums file"
        default: "https://github.com/{{ _node_exporter_repo }}/releases/download/v{{ node_exporter_version }}/sha256sums.txt"
      node_exporter_web_listen_address:
        description: "Address on which node exporter will listen"
        default: "0.0.0.0:9100"
      node_exporter_web_telemetry_path:
        description: "Path under which to expose metrics"
        default: "/metrics"
      node_exporter_enabled_collectors:
        description:
          - "List of dicts defining additionally enabled collectors and their configuration."
          - "It adds collectors to L(those enabled by default,https://github.com/prometheus/node_exporter#enabled-by-default)."
        type: "list"
        default:
          - systemd
          - textfile:
              directory: "{{ node_exporter_textfile_dir }}"
      node_exporter_disabled_collectors:
        description:
          - "List of disabled collectors."
          - "By default node_exporter disables collectors listed L(here,https://github.com/prometheus/node_exporter#disabled-by-default)."
        type: "list"
        elements: "str"
      node_exporter_textfile_dir:
        description:
          - "Directory used by the L(Textfile Collector,https://github.com/prometheus/node_exporter#textfile-collector)."
          - "To get permissions to write metrics in this directory, users must be in C(node-exp) system group."
          - "B(Note:) More information in TROUBLESHOOTING.md guide."
        default: "/var/lib/node_exporter"
      node_exporter_tls_server_config:
        description:
          - "Configuration for TLS authentication."
          - "Keys and values are the same as in L(node_exporter docs,https://prometheus.io/docs/prometheus/latest/configuration/https/)."
        type: "dict"
      node_exporter_http_server_config:
        description:
          - "Config for HTTP/2 support."
          - "Keys and values are the same as in L(node_exporter docs,https://prometheus.io/docs/prometheus/latest/configuration/https/)."
        type: "dict"
      node_exporter_basic_auth_users:
        description: "Dictionary of users and password for basic authentication. Passwords are automatically hashed with bcrypt."
        type: "dict"
      node_exporter_binary_install_dir:
        description:
          - "I(Advanced)"
          - "Directory to install node_exporter binary"
        default: "/usr/local/bin"
      node_exporter_system_group:
        description:
          - "I(Advanced)"
          - "System group for node exporter"
        default: "node-exp"
      node_exporter_system_user:
        description:
          - "I(Advanced)"
          - "Node exporter user"
        default: "node-exp"
