---
- name: Create the pushgateway group
  ansible.builtin.group:
    name: "{{ pushgateway_system_group }}"
    state: present
    system: true
  when: pushgateway_system_group != "root"

- name: Create the pushgateway user
  ansible.builtin.user:
    name: "{{ pushgateway_system_user }}"
    groups: "{{ pushgateway_system_group }}"
    append: true
    shell: /usr/sbin/nologin
    system: true
    create_home: false
    home: /
  when: pushgateway_system_user != "root"

- name: Get binary
  when:
    - pushgateway_binary_local_dir | length == 0
    - not pushgateway_skip_install
  block:

    - name: Download pushgateway binary to local folder
      become: false
      ansible.builtin.get_url:
        url: "{{ pushgateway_binary_url }}"
        dest: "/tmp/pushgateway-{{ pushgateway_version }}.linux-{{ go_arch }}.tar.gz"
        checksum: "sha256:{{ __pushgateway_checksum }}"
        mode: '0644'
      register: _download_binary
      until: _download_binary is succeeded
      retries: 5
      delay: 2
      delegate_to: localhost
      check_mode: false

    - name: Unpack pushgateway binary
      become: false
      ansible.builtin.unarchive:
        src: "/tmp/pushgateway-{{ pushgateway_version }}.linux-{{ go_arch }}.tar.gz"
        dest: "/tmp"
        creates: "/tmp/pushgateway-{{ pushgateway_version }}.linux-{{ go_arch }}/pushgateway"
      delegate_to: localhost
      check_mode: false

    - name: Propagate pushgateway binaries
      ansible.builtin.copy:
        src: "/tmp/pushgateway-{{ pushgateway_version }}.linux-{{ go_arch }}/pushgateway"
        dest: "{{ pushgateway_binary_install_dir }}/pushgateway"
        mode: 0755
        owner: root
        group: root
      notify: restart pushgateway
      when: not ansible_check_mode

- name: Propagate locally distributed pushgateway binary
  ansible.builtin.copy:
    src: "{{ pushgateway_binary_local_dir }}/pushgateway"
    dest: "{{ pushgateway_binary_install_dir }}/pushgateway"
    mode: 0755
    owner: root
    group: root
  when:
    - pushgateway_binary_local_dir | length > 0
    - not pushgateway_skip_install
  notify: restart pushgateway
