---
nvidia_gpu_exporter_version: 1.3.0
nvidia_gpu_exporter_binary_url: "https://github.com/{{ _nvidia_gpu_exporter_repo }}/releases/download/v{{ nvidia_gpu_exporter_version }}/\
                           nvidia_gpu_exporter_{{ nvidia_gpu_exporter_version }}_{{ ansible_facts['system'] | lower }}_{{ _nvidia_gpu_exporter_go_ansible_arch }}.tar.gz"
nvidia_gpu_exporter_checksums_url: "https://github.com/{{ _nvidia_gpu_exporter_repo }}/releases/download/v{{ nvidia_gpu_exporter_version }}/checksums.txt"

nvidia_gpu_exporter_web_listen_address: "0.0.0.0:9835"
nvidia_gpu_exporter_web_telemetry_path: "/metrics"

nvidia_gpu_exporter_binary_install_dir: "/usr/local/bin"
nvidia_gpu_exporter_system_group: "nvidia-gpu-exp"
nvidia_gpu_exporter_system_user: "{{ nvidia_gpu_exporter_system_group }}"

nvidia_gpu_exporter_config_dir: "/etc/nvidia_gpu_exporter"
# Local path to stash the archive and its extraction
nvidia_gpu_exporter_local_cache_path: "/tmp/nvidia_gpu_exporter-{{ ansible_facts['system'] | lower }}-{{ _nvidia_gpu_exporter_go_ansible_arch }}/{{ nvidia_gpu_exporter_version }}"
