---
- name: Create the node_exporter group
  ansible.builtin.group:
    name: "{{ node_exporter_system_group }}"
    state: present
    system: true
  when: node_exporter_system_group != "root"

- name: Create the node_exporter user
  ansible.builtin.user:
    name: "{{ node_exporter_system_user }}"
    groups: "{{ node_exporter_system_group }}"
    append: true
    shell: /usr/sbin/nologin
    system: true
    create_home: false
    home: /
  when: node_exporter_system_user != "root"

- name: Discover latest version
  when:
    - node_exporter_binary_local_dir | length == 0
    - not node_exporter_skip_install
  block:

    - name: Download node_exporter binary to local folder
      become: false
      ansible.builtin.get_url:
        url: "{{ node_exporter_binary_url }}"
        dest: "/tmp/node_exporter-{{ node_exporter_version }}.linux-{{ go_arch }}.tar.gz"
        checksum: "sha256:{{ __node_exporter_checksum }}"
        mode: '0644'
      register: _download_binary
      until: _download_binary is succeeded
      retries: 5
      delay: 2
      delegate_to: localhost
      check_mode: false

    - name: Unpack node_exporter binary
      become: false
      ansible.builtin.unarchive:
        src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-{{ go_arch }}.tar.gz"
        dest: "/tmp"
        creates: "/tmp/node_exporter-{{ node_exporter_version }}.linux-{{ go_arch }}/node_exporter"
      delegate_to: localhost
      check_mode: false

    - name: Propagate node_exporter binaries
      ansible.builtin.copy:
        src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-{{ go_arch }}/node_exporter"
        dest: "{{ node_exporter_binary_install_dir }}/node_exporter"
        mode: 0755
        owner: root
        group: root
      notify: restart node_exporter
      when: not ansible_check_mode

- name: Propagate locally distributed node_exporter binary
  ansible.builtin.copy:
    src: "{{ node_exporter_binary_local_dir }}/node_exporter"
    dest: "{{ node_exporter_binary_install_dir }}/node_exporter"
    mode: 0755
    owner: root
    group: root
  when:
    - node_exporter_binary_local_dir | length > 0
    - not node_exporter_skip_install
  notify: restart node_exporter
