---
galaxy_info:
  author: "Prometheus Community"
  description: "Prometheus Systemd Exporter"
  license: "Apache"
  min_ansible_version: "2.9"
  platforms:
    - name: "Ubuntu"
      versions:
        - "focal"
        - "jammy"
        - "xenial"
        - "noble"
    - name: "Debian"
      versions:
        - "bullseye"
    - name: "EL"
      versions:
        - "8"
        - "9"
    - name: "Fedora"
      versions:
        - "39"
        - "40"
  galaxy_tags:
    - "monitoring"
    - "prometheus"
    - "exporter"
    - "metrics"
    - "systemd"
