---
- name: "Validate invocation of _common role"
  ansible.builtin.assert:
    that:
      - "ansible_parent_role_names is defined"
      - "ansible_parent_role_names | default() | length > 0"
    fail_msg: "Error: The '_common' role is a internal role and cannot be invoked directly."
  tags:
    - always

- name: "Check for deprecated skip_install variable"
  ansible.builtin.assert:
    that:
      - __common_parent_role_short_name ~ '_skip_install' not in vars
    fail_msg: "The variable {{ __common_parent_role_short_name ~ '_skip_install' }} is deprecated.
               Please use `--skip-tags {{ __common_parent_role_short_name }}_install` instead to skip the installation."
  tags:
    - "{{ ansible_parent_role_names | first | regex_replace(ansible_collection_name ~ '.', '') }}"
    - configure
    - "{{ ansible_parent_role_names | first | regex_replace(ansible_collection_name ~ '.', '') }}_configure"

- name: "Check for deprecated binary_local_dir variable"
  ansible.builtin.assert:
    that:
      - __common_parent_role_short_name ~ '_binary_local_dir' not in vars
    fail_msg: "The variable {{ __common_parent_role_short_name ~ '_binary_local_dir' }} is deprecated.
               Please use the variable {{ __common_parent_role_short_name ~ '_local_cache_path' }} instead"
  tags:
    - "{{ ansible_parent_role_names | first | regex_replace(ansible_collection_name ~ '.', '') }}"
    - configure
    - "{{ ansible_parent_role_names | first | regex_replace(ansible_collection_name ~ '.', '') }}_configure"

- name: "Check for deprecated archive_path variable"
  ansible.builtin.assert:
    that:
      - __common_parent_role_short_name ~ '_archive_path' not in vars
    fail_msg: "The variable {{ __common_parent_role_short_name ~ '_archive_path' }} is deprecated.
               Please use the variable {{ __common_parent_role_short_name ~ '_local_cache_path' }} instead"
  tags:
    - "{{ ansible_parent_role_names | first | regex_replace(ansible_collection_name ~ '.', '') }}"
    - configure
    - "{{ ansible_parent_role_names | first | regex_replace(ansible_collection_name ~ '.', '') }}_configure"

- name: Assert usage of systemd as an init system
  ansible.builtin.assert:
    that: ansible_service_mgr == 'systemd'
    msg: "This module only works with systemd"
  tags:
    - "{{ ansible_parent_role_names | first | regex_replace(ansible_collection_name ~ '.', '') }}"
    - configure
    - "{{ ansible_parent_role_names | first | regex_replace(ansible_collection_name ~ '.', '') }}_configure"
    - install
    - "{{ ansible_parent_role_names | first | regex_replace(ansible_collection_name ~ '.', '') }}_install"

- name: Install dependencies
  become: true
  ansible.builtin.package:
    name: "{{ _common_dependencies }}"
    state: present
  when: (_common_dependencies)
  tags:
    - "{{ ansible_parent_role_names | first | regex_replace(ansible_collection_name ~ '.', '') }}"
    - configure
    - "{{ ansible_parent_role_names | first | regex_replace(ansible_collection_name ~ '.', '') }}_configure"
    - install
    - "{{ ansible_parent_role_names | first | regex_replace(ansible_collection_name ~ '.', '') }}_install"

- name: Gather package facts
  ansible.builtin.package_facts:
  when: "not 'packages' in ansible_facts"
  tags:
    - "{{ ansible_parent_role_names | first | regex_replace(ansible_collection_name ~ '.', '') }}"
    - configure
    - "{{ ansible_parent_role_names | first | regex_replace(ansible_collection_name ~ '.', '') }}_configure"
    - install
    - "{{ ansible_parent_role_names | first | regex_replace(ansible_collection_name ~ '.', '') }}_install"
