---
- name: Run role
  hosts: all
  any_errors_fatal: true
  roles:
    - ansible-blackbox-exporter
  vars:
    blackbox_exporter_web_listen_address: "127.0.0.1:9000"
    blackbox_exporter_cli_flags:
      log.level: "warn"
    blackbox_exporter_configuration_modules:
      tcp_connect:
        prober: tcp
        timeout: 5s
