---
- name: Preflight
  ansible.builtin.include_tasks:
    file: preflight.yml
  tags:
    - consul_exporter
    - install
    - configure
    - run
    - consul_exporter_install
    - consul_exporter_configure
    - consul_exporter_run

- name: Install
  ansible.builtin.include_role:
    name: prometheus.prometheus._common
    tasks_from: install.yml
  vars:
    _common_local_cache_path: "{{ consul_exporter_local_cache_path }}"
    _common_binaries: "{{ _consul_exporter_binaries }}"
    _common_binary_install_dir: "{{ consul_exporter_binary_install_dir }}"
    _common_binary_url: "{{ consul_exporter_binary_url }}"
    _common_checksums_url: "{{ consul_exporter_checksums_url }}"
    _common_system_group: "{{ consul_exporter_system_group }}"
    _common_system_user: "{{ consul_exporter_system_user }}"
    _common_config_dir: "{{ consul_exporter_config_dir }}"
    _common_binary_unarchive_opts: ['--strip-components=1']
  tags:
    - consul_exporter
    - install
    - consul_exporter_install

- name: SELinux
  ansible.builtin.include_role:
    name: prometheus.prometheus._common
    tasks_from: selinux.yml
  vars:
    _common_selinux_port: "{{ consul_exporter_web_listen_address | urlsplit('port') }}"
  when: ansible_facts['selinux'].status == "enabled"
  tags:
    - consul_exporter_configure

- name: Configure
  ansible.builtin.include_role:
    name: prometheus.prometheus._common
    tasks_from: configure.yml
  vars:
    _common_system_user: "{{ consul_exporter_system_user }}"
    _common_system_group: "{{ consul_exporter_system_group }}"
    _common_config_dir: "{{ consul_exporter_config_dir }}"
    _common_tls_server_config: "{{ consul_exporter_tls_server_config }}"
    _common_http_server_config: "{{ consul_exporter_http_server_config }}"
    _common_basic_auth_users: "{{ consul_exporter_basic_auth_users }}"
  tags:
    - consul_exporter_configure

- name: Ensure consul Exporter is enabled on boot
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: consul_exporter
    enabled: true
    state: started
  when:
    - not ansible_check_mode
  tags:
    - consul_exporter_run
