---
_smartctl_exporter_go_ansible_arch: "{{ {'i386': '386',
                                     'x86_64': 'amd64',
                                     'aarch64': 'arm64',
                                     'armv7l': 'armv7',
                                     'armv6l': 'armv6'}.get(ansible_architecture, ansible_architecture) }}"
_smartctl_exporter_repo: "prometheus-community/smartctl_exporter"
_github_api_headers: "{{ {'GITHUB_TOKEN': lookup('ansible.builtin.env', 'GITHUB_TOKEN')} if (lookup('ansible.builtin.env', 'GITHUB_TOKEN')) else {} }}"
_smartctl_exporter_binaries: ['smartctl_exporter']
