---
- name: Common preflight
  ansible.builtin.include_role:
    name: prometheus.prometheus._common
    tasks_from: preflight.yml
  vars:
    _common_web_listen_address: "{{ nvidia_gpu_exporter_web_listen_address }}"

- name: Discover latest version
  ansible.builtin.set_fact:
    nvidia_gpu_exporter_version: "{{ (lookup('url', 'https://api.github.com/repos/{{ _nvidia_gpu_exporter_repo }}/releases/latest', headers=_nvidia_gpu_exporter_github_api_headers,
                            split_lines=False) | from_json).get('tag_name') | replace('v', '') }}"
  run_once: true
  until: nvidia_gpu_exporter_version is version('0.0.0', '>=')
  retries: 10
  when:
    - nvidia_gpu_exporter_version == "latest"
  tags:
    - nvidia_gpu_exporter
    - install
    - nvidia_gpu_exporter_install
    - download
    - nvidia_gpu_exporter_download
