---
# yamllint disable rule:line-length
argument_specs:
  main:
    short_description: "Deploy and manage Prometheus blackbox exporter"
    description:
      - "Deploy and manage Prometheus blackbox exporter which allows blackbox probing of endpoints over HTTP, HTTPS, DNS, TCP and ICMP."
    author:
      - "Prometheus Community"
    options:
      blackbox_exporter_version:
        description: "Blackbox exporter package version. Also accepts latest as parameter."
        default: "0.25.0"
      blackbox_exporter_binary_url:
        description: "URL of the blackbox_exporter binaries .tar.gz file"
        default: "https://github.com/{{ _blackbox_exporter_repo }}/releases/download/v{{ blackbox_exporter_version }}/blackbox_exporter-{{ blackbox_exporter_version }}.{{ ansible_system | lower }}-{{ _blackbox_exporter_go_ansible_arch }}.tar.gz"
      blackbox_exporter_checksums_url:
        description: "URL of the blackbox exporter checksums file"
        default: "https://github.com/{{ _blackbox_exporter_repo }}/releases/download/v{{ blackbox_exporter_version }}/sha256sums.txt"
      blackbox_exporter_web_listen_address:
        description: "Address on which blackbox exporter will be listening"
        default: "0.0.0.0:9115"
      blackbox_exporter_cli_flags:
        description: "Additional configuration flags passed to blackbox exporter binary at startup"
        type: "dict"
      blackbox_exporter_configuration_modules:
        description: "Endpoints configuration"
        type: "dict"
        default:
          http_2xx:
            prober: http
            timeout: 5s
            http:
              method: GET
              valid_status_codes: []
      blackbox_exporter_config_dir:
        description: "Path to directory with blackbox_exporter configuration"
        default: "/etc/blackbox_exporter"
      blackbox_exporter_binary_install_dir:
        description:
          - "I(Advanced)"
          - "Directory to install blackbox_exporter binary"
        default: "/usr/local/bin"
      blackbox_exporter_system_user:
        description: "The user the exporter runs as"
        default: "blackbox-exp"
      blackbox_exporter_system_group:
        description: "The group the exporter runs as"
        default: "blackbox-exp"
      blackbox_exporter_local_cache_path:
        description: 'Local path to stash the archive and its extraction'
        default: "/tmp/blackbox_exporter-{{ ansible_system | lower }}-{{ _blackbox_exporter_go_ansible_arch }}/{{ blackbox_exporter_version }}"
