---
- name: Create the mysqld_exporter group
  ansible.builtin.group:
    name: "{{ mysqld_exporter_system_group }}"
    state: present
    system: true
  when: mysqld_exporter_system_group != "root"

- name: Create the mysqld_exporter user
  ansible.builtin.user:
    name: "{{ mysqld_exporter_system_user }}"
    groups: "{{ mysqld_exporter_system_group }}"
    append: true
    shell: /usr/sbin/nologin
    system: true
    create_home: false
    home: /
  when: mysqld_exporter_system_user != "root"

- name: Get binary
  when:
    - mysqld_exporter_binary_local_dir | length == 0
    - not mysqld_exporter_skip_install
  block:

    - name: Download mysqld_exporter binary to local folder
      become: false
      ansible.builtin.get_url:
        url: "{{ mysqld_exporter_binary_url }}"
        dest: "{{ mysqld_exporter_archive_path }}/mysqld_exporter-{{ mysqld_exporter_version }}.linux-{{ go_arch }}.tar.gz"
        checksum: "sha256:{{ __mysqld_exporter_checksum }}"
        mode: '0644'
      register: _download_binary
      until: _download_binary is succeeded
      retries: 5
      delay: 2
      delegate_to: localhost
      check_mode: false

    - name: Unpack mysqld_exporter binary
      become: false
      ansible.builtin.unarchive:
        src: "{{ mysqld_exporter_archive_path }}/mysqld_exporter-{{ mysqld_exporter_version }}.linux-{{ go_arch }}.tar.gz"
        dest: "{{ mysqld_exporter_archive_path }}"
        creates: "{{ mysqld_exporter_archive_path }}/mysqld_exporter-{{ mysqld_exporter_version }}.linux-{{ go_arch }}/mysqld_exporter"
        extra_opts:
          - --no-same-owner
      delegate_to: localhost
      check_mode: false

    - name: Propagate mysqld_exporter binaries
      ansible.builtin.copy:
        src: "{{ mysqld_exporter_archive_path }}/mysqld_exporter-{{ mysqld_exporter_version }}.linux-{{ go_arch }}/mysqld_exporter"
        dest: "{{ mysqld_exporter_binary_install_dir }}/mysqld_exporter"
        mode: '0755'
        owner: root
        group: root
      notify: restart mysqld_exporter
      when: not ansible_check_mode

- name: Propagate locally distributed mysqld_exporter binary
  ansible.builtin.copy:
    src: "{{ mysqld_exporter_binary_local_dir }}/mysqld_exporter"
    dest: "{{ mysqld_exporter_binary_install_dir }}/mysqld_exporter"
    mode: '0755'
    owner: root
    group: root
  when:
    - mysqld_exporter_binary_local_dir | length > 0
    - not mysqld_exporter_skip_install
  notify: restart mysqld_exporter
