---
- name: Common preflight
  ansible.builtin.include_role:
    name: prometheus.prometheus._common
    tasks_from: preflight.yml

- name: Assert that used version supports listen address type
  ansible.builtin.assert:
    that:
      - >-
        mysqld_exporter_web_listen_address is string
        or
        (
          mysqld_exporter_version is version('0.15.0', '>=') and
          mysqld_exporter_web_listen_address | type_debug == "list"
        )

- name: Naive assertion of proper listen address
  ansible.builtin.assert:
    that:
      - >-
        [mysqld_exporter_web_listen_address] |
          flatten |
          reject('match', '.+:\\d+$') |
          list |
          length == 0

- name: Assert collectors are not both disabled and enabled at the same time
  ansible.builtin.assert:
    that:
      - "item not in mysqld_exporter_enabled_collectors"
  with_items: "{{ mysqld_exporter_disabled_collectors }}"

- name: Assert that TLS config is correct
  when: mysqld_exporter_tls_server_config | length > 0
  block:
    - name: Assert that TLS key and cert path are set
      ansible.builtin.assert:
        that:
          - "mysqld_exporter_tls_server_config.cert_file is defined"
          - "mysqld_exporter_tls_server_config.key_file is defined"

    - name: Check existence of TLS cert file
      ansible.builtin.stat:
        path: "{{ mysqld_exporter_tls_server_config.cert_file }}"
      register: __mysqld_exporter_cert_file

    - name: Check existence of TLS key file
      ansible.builtin.stat:
        path: "{{ mysqld_exporter_tls_server_config.key_file }}"
      register: __mysqld_exporter_key_file

    - name: Assert that TLS key and cert are present
      ansible.builtin.assert:
        that:
          - "__mysqld_exporter_cert_file.stat.exists"
          - "__mysqld_exporter_key_file.stat.exists"

- name: Discover latest version
  ansible.builtin.set_fact:
    mysqld_exporter_version: "{{ (lookup('url', 'https://api.github.com/repos/{{ _mysqld_exporter_repo }}/releases/latest', headers=_github_api_headers,
                              split_lines=False) | from_json).get('tag_name') | replace('v', '') }}"
  run_once: true
  until: mysqld_exporter_version is version('0.0.0', '>=')
  retries: 10
  when:
    - mysqld_exporter_version == "latest"
  tags:
    - mysqld_exporter
    - install
    - mysqld_exporter_install
    - download
    - mysqld_exporter_download
