---
# yamllint disable rule:line-length
argument_specs:
  main:
    short_description: "Prometheus MySQLd Exporter"
    description:
      - "Deploy prometheus L(mysqld_exporter,https://github.com/prometheus/mysqld_exporter) using ansible"
    author:
      - "Prometheus Community"
    options:
      mysqld_exporter_version:
        description: "MySQLd exporter package version. Also accepts latest as parameter."
        default: "0.15.1"
      mysqld_exporter_binary_url:
        description: "URL of the mysqld_exporter binaries .tar.gz file"
        default: "https://github.com/{{ _mysqld_exporter_repo }}/releases/download/v{{ mysqld_exporter_version }}/mysqld_exporter-{{ mysqld_exporter_version }}.{{ ansible_system | lower }}-{{ _mysqld_exporter_go_ansible_arch }}.tar.gz"
      mysqld_exporter_checksums_url:
        description: "URL of the mysqld_exporter checksums file"
        default: "https://github.com/{{ _mysqld_exporter_repo }}/releases/download/v{{ mysqld_exporter_version }}/sha256sums.txt"
      mysqld_exporter_web_listen_address:
        description: "Address on which mysqld_exporter will listen"
        default: "0.0.0.0:9104"
      mysqld_exporter_web_telemetry_path:
        description: "Path under which to expose metrics"
        default: "/metrics"
      mysqld_exporter_config_dir:
        description: "Path to directory with mysqld_exporter configuration"
        default: "/etc/mysqld_exporter"
      mysqld_exporter_config_file:
        description: "The filename of the exporter mysql config file"
        default: "mysqld_exporter.cnf"
      mysqld_exporter_host:
        description: "The target MySQL host"
      mysqld_exporter_port:
        description: "The target MySQL port"
      mysqld_exporter_socket:
        description: "The target MySQL unix socket"
        default: "/run/mysqld/mysqld.sock"
      mysqld_exporter_username:
        description: "The username for MySQL login"
        default: "exporter"
      mysqld_exporter_password:
        description: "The password for MySQL login"
        default: "secret"
      mysqld_exporter_enabled_collectors:
        description:
          - "List of dicts defining additionally enabled collectors and their configuration."
          - "It adds collectors to L(those enabled by default,https://github.com/prometheus/mysqld_exporter#enabled-by-default)."
        type: "list"
        default: []
      mysqld_exporter_disabled_collectors:
        description:
          - "List of disabled collectors."
          - "By default mysqld_exporter disables collectors listed L(here,https://github.com/prometheus/mysqld_exporter#disabled-by-default)."
        type: "list"
        elements: "str"
      mysqld_exporter_tls_server_config:
        description:
          - "Configuration for TLS authentication."
          - "Keys and values are the same as in L(mysqld_exporter docs,https://github.com/prometheus/mysqld_exporter/blob/master/https/README.md#sample-config)."
        type: "dict"
      mysqld_exporter_http_server_config:
        description:
          - "Config for HTTP/2 support."
          - "Keys and values are the same as in L(mysqld_exporter docs,https://github.com/prometheus/mysqld_exporter/blob/master/https/README.md#sample-config)."
        type: "dict"
      mysqld_exporter_basic_auth_users:
        description: "Dictionary of users and password for basic authentication. Passwords are automatically hashed with bcrypt."
        type: "dict"
      mysqld_exporter_binary_install_dir:
        description:
          - "I(Advanced)"
          - "Directory to install mysqld_exporter binary"
        default: "/usr/local/bin"
      mysqld_exporter_system_group:
        description:
          - "I(Advanced)"
          - "System group for MySQLd Exporter"
        default: "mysqld-exp"
      mysqld_exporter_system_user:
        description:
          - "I(Advanced)"
          - "MySQLd Exporter user"
        default: "mysqld-exp"
      mysqld_exporter_local_cache_path:
        description: "Local path to stash the archive and its extraction"
        default: "/tmp/mysqld_exporter-{{ ansible_system | lower }}-{{ _mysqld_exporter_go_ansible_arch }}/{{ mysqld_exporter_version }}"
