---
- name: Preflight
  ansible.builtin.include_tasks:
    file: preflight.yml
  tags:
    - smokeping_prober_install
    - smokeping_prober_configure
    - smokeping_prober_run

- name: Install
  ansible.builtin.include_role:
    name: prometheus.prometheus._common
    tasks_from: install.yml
  vars:
    _common_local_cache_path: "{{ smokeping_prober_local_cache_path }}"
    _common_binaries: "{{ _smokeping_prober_binaries }}"
    _common_binary_install_dir: "{{ smokeping_prober_binary_install_dir }}"
    _common_binary_url: "{{ smokeping_prober_binary_url }}"
    _common_checksums_url: "{{ smokeping_prober_checksums_url }}"
    _common_system_group: "{{ smokeping_prober_system_group }}"
    _common_system_user: "{{ smokeping_prober_system_user }}"
    _common_config_dir: "{{ smokeping_prober_config_dir }}"
    _common_binary_unarchive_opts: ['--strip-components=1']
  tags:
    - smokeping_prober_install

- name: SELinux
  ansible.builtin.include_role:
    name: prometheus.prometheus._common
    tasks_from: selinux.yml
  vars:
    _common_selinux_port: "{{ smokeping_prober_web_listen_address | urlsplit('port') }}"
  when: ansible_selinux.status == "enabled"
  tags:
    - smokeping_prober_configure

- name: Configure
  ansible.builtin.include_tasks:
    file: configure.yml
  tags:
    - smokeping_prober_configure

- name: Ensure Smokeping Prober is enabled on boot
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: smokeping_prober
    enabled: true
    state: started
  when:
    - not ansible_check_mode
  tags:
    - smokeping_prober_run
