---
- name: Copy the systemd_exporter systemd service file
  ansible.builtin.template:
    src: systemd_exporter.service.j2
    dest: /etc/systemd/system/systemd_exporter.service
    owner: root
    group: root
    mode: 0644
  notify: restart systemd_exporter

- name: Allow systemd_exporter port in SELinux on RedHat OS family
  community.general.seport:
    ports: "{{ systemd_exporter_web_listen_address.split(':')[-1] }}"
    proto: tcp
    setype: http_port_t
    state: present
  when:
    - ansible_version.full is version_compare('2.4', '>=')
    - ansible_selinux.status == "enabled"
