---
- name: Create the systemd_exporter group
  ansible.builtin.group:
    name: "{{ systemd_exporter_system_group }}"
    state: present
    system: true
  when: systemd_exporter_system_group != "root"

- name: Create the systemd_exporter user
  ansible.builtin.user:
    name: "{{ systemd_exporter_system_user }}"
    groups: "{{ systemd_exporter_system_group }}"
    append: true
    shell: /usr/sbin/nologin
    system: true
    create_home: false
    home: /
  when: systemd_exporter_system_user != "root"

- name: Get systemd exporter binary
  when:
    - systemd_exporter_binary_local_dir | length == 0
    - not systemd_exporter_skip_install
  block:
    - name: Download systemd_exporter binary to local folder
      become: false
      ansible.builtin.get_url:
        url: "{{ systemd_exporter_binary_url }}"
        dest: "/tmp/systemd_exporter-{{ systemd_exporter_version }}.linux-{{ go_arch }}.tar.gz"
        checksum: "sha256:{{ _systemd_exporter_checksum }}"
        mode: '0644'
      register: _download_binary
      until: _download_binary is succeeded
      retries: 5
      delay: 2
      delegate_to: localhost
      check_mode: false

    - name: Unpack systemd_exporter binary
      become: false
      ansible.builtin.unarchive:
        src: "/tmp/systemd_exporter-{{ systemd_exporter_version }}.linux-{{ go_arch }}.tar.gz"
        dest: "/tmp"
        creates: "/tmp/systemd_exporter-{{ systemd_exporter_version }}.linux-{{ go_arch }}/systemd_exporter"
      delegate_to: localhost
      check_mode: false

    - name: Propagate systemd_exporter binaries
      ansible.builtin.copy:
        src: "/tmp/systemd_exporter-{{ systemd_exporter_version }}.linux-{{ go_arch }}/systemd_exporter"
        dest: "{{ systemd_exporter_binary_install_dir }}/systemd_exporter"
        mode: 0755
        owner: root
        group: root
      notify: restart systemd_exporter
      when: not ansible_check_mode

- name: Propagate locally distributed systemd_exporter binary
  ansible.builtin.copy:
    src: "{{ systemd_exporter_binary_local_dir }}/systemd_exporter"
    dest: "{{ systemd_exporter_binary_install_dir }}/systemd_exporter"
    mode: 0755
    owner: root
    group: root
  when:
    - systemd_exporter_binary_local_dir | length > 0
    - not systemd_exporter_skip_install
  notify: restart systemd_exporter
