---
- name: Create the mongodb_exporter group
  ansible.builtin.group:
    name: "{{ mongodb_exporter_system_group }}"
    state: present
    system: true
  when: mongodb_exporter_system_group not in ["root", 'mongodb', 'nogroup']

- name: Create the mongodb_exporter user
  ansible.builtin.user:
    name: "{{ mongodb_exporter_system_user }}"
    groups: "{{ mongodb_exporter_system_group }}"
    append: true
    shell: /usr/sbin/nologin
    system: true
    create_home: false
    home: /
  when: mongodb_exporter_system_user not in ["root", 'mongodb', 'nobody']

- name: Get binary
  when:
    - mongodb_exporter_binary_local_dir | length == 0
    - not mongodb_exporter_skip_install
  block:

    - name: Download mongodb_exporter binary to local folder
      become: false
      ansible.builtin.get_url:
        url: "{{ mongodb_exporter_binary_url }}"
        dest: "{{ mongodb_exporter_archive_path }}/mongodb_exporter-{{ mongodb_exporter_version }}.linux-{{ go_arch }}.tar.gz"
        checksum: "sha256:{{ __mongodb_exporter_checksum }}"
        mode: '0644'
      register: _download_binary
      until: _download_binary is succeeded
      retries: 5
      delay: 2
      delegate_to: localhost
      check_mode: false

    - name: Unpack mongodb_exporter binary
      become: false
      ansible.builtin.unarchive:
        src: "{{ mongodb_exporter_archive_path }}/mongodb_exporter-{{ mongodb_exporter_version }}.linux-{{ go_arch }}.tar.gz"
        dest: "{{ mongodb_exporter_archive_path }}"
        creates: "{{ mongodb_exporter_archive_path }}/mongodb_exporter-{{ mongodb_exporter_version }}.linux-{{ go_arch }}/mongodb_exporter"
      delegate_to: localhost
      check_mode: false

    - name: Propagate mongodb_exporter binaries
      ansible.builtin.copy:
        src: "{{ mongodb_exporter_archive_path }}/mongodb_exporter-{{ mongodb_exporter_version }}.linux-{{ go_arch }}/mongodb_exporter"
        dest: "{{ mongodb_exporter_binary_install_dir }}/mongodb_exporter"
        mode: 0755
        owner: root
        group: root
      notify: restart mongodb_exporter
      when: not ansible_check_mode

- name: Propagate locally distributed mongodb_exporter binary
  ansible.builtin.copy:
    src: "{{ mongodb_exporter_binary_local_dir }}/mongodb_exporter"
    dest: "{{ mongodb_exporter_binary_install_dir }}/mongodb_exporter"
    mode: 0755
    owner: root
    group: root
  when:
    - mongodb_exporter_binary_local_dir | length > 0
    - not mongodb_exporter_skip_install
  notify: restart mongodb_exporter
