---
name: Collection Docs
concurrency:
  group: docs-push-${{ github.sha }}
  cancel-in-progress: true
on:
  push:
    branches:
      - main
    tags:
      - '*'
  # Run CI once per day (at 06:00 UTC)
  schedule:
    - cron: '0 6 * * *'
  # Allow manual trigger (for newer antsibull-docs, sphinx-ansible-theme, ... versions)
  workflow_dispatch:

jobs:
  get-tags:
    runs-on: ubuntu-latest
    outputs:
      latest: ${{ steps.get-latest-tag.outputs.latest_tag }}
    steps:
      - name: Get the latest tag
        id: get-latest-tag
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd  # v8.0.0
        with:
          script: |
            const latestTag = await github.rest.repos.listTags({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 1
            });
            core.setOutput('latest_tag', latestTag.data[0].name);

  build-docs:
    name: Build Ansible Docs
    needs: get-tags
    permissions:
      contents: read
    uses: ansible-community/github-docs-build/.github/workflows/_shared-docs-build-push.yml@main
    with:
      collection-name: prometheus.prometheus
      init-lenient: false
      init-fail-on-error: true
      squash-hierarchy: true
      init-project: Prometheus.Prometheus Collection
      init-copyright: Prometheus.Prometheus Contributors
      init-title: Prometheus.Prometheus Collection Documentation
      init-html-short-title: Prometheus.Prometheus Collection Docs
      init-extra-html-theme-options: |
        documentation_home_url=https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/tag/${{ needs.get-tags.outputs.latest }}

  publish-docs-gh-pages:
    # for now we won't run this on forks
    if: github.repository == 'prometheus-community/ansible'
    permissions:
      contents: write
      pages: write
      id-token: write
    needs: [build-docs]
    name: Publish Ansible Docs
    uses: ansible-community/github-docs-build/.github/workflows/_shared-docs-build-publish-gh-pages.yml@main
    with:
      artifact-name: ${{ needs.build-docs.outputs.artifact-name }}
      publish-gh-pages-branch: true
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
