---
name: Ansible collection publish
on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd  # v5.0.1

      - name: "Build the collection"
        id: build-collection
        uses: ansible-community/github-action-build-collection@main

      - name: "Upload built collection to release"
        uses: svenstaro/upload-release-action@81c65b7cd4de9b2570615ce3aad67a41de5b1a13  # 2.11.2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ steps.build-collection.outputs.artifact-filename }}
          file_glob: true
          tag: ${{ github.ref }}
          overwrite: true

      - name: "Publish collection on galaxy"
        uses: ansible/ansible-publish-action@a56a0328c92c1d4feedf5bd7f7cf7ec7a4ae3f09  # v1.0.0
        with:
          api_key: ${{ secrets.ANSIBLE_GALAXY_API_KEY }}
