---
name: Ansible collection publish
on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: "Build the collection"
        id: build-collection
        uses: ansible-community/github-action-build-collection@main

      - name: "Upload built collection to release"
        uses: svenstaro/upload-release-action@6b7fa9f267e90b50a19fef07b3596790bb941741  # 2.11.3
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ steps.build-collection.outputs.artifact-filename }}
          file_glob: true
          tag: ${{ github.ref }}
          overwrite: true

      - name: "Publish collection on galaxy"
        uses: ansible/ansible-publish-action@a56a0328c92c1d4feedf5bd7f7cf7ec7a4ae3f09  # v1.0.0
        with:
          api_key: ${{ secrets.ANSIBLE_GALAXY_API_KEY }}
